const TodoConstant = {
  ADD_TODO: 'ADD_TODO',
  TOGGLE_COMPLETE: 'TOGGLE_COMPLETE',
  SHOW_FILTER: 'SHOW_FILTER',
  FILTER: {
    SHOW_ALL: 'SHOW_ALL',
    SHOW_ACTIVE: 'SHOW_ACTIVE',
    SHOW_COMPLETED: "SHOW_COMPLETED"
  }
};

export default TodoConstant;